const express = require("express")
const partnerRoutes = express()
const { signup, otpVerification, loginVerification, partnerKycUpload, addProperty, listProperty, detailProperty,findParnter,partnerProfile ,partnerimage,addDescription,findProperty,updateProperty,deletepropertyImage,fetchBuyer,hideTheProperty,resendOpt} = require('../Controller/partnerController')
const { partnerTokenVerified } = require("../Middleware/auth")
partnerRoutes.post("/signup", signup)
partnerRoutes.post("/otpVerification", otpVerification)
partnerRoutes.post('/login', loginVerification)
partnerRoutes.patch('/partnerKycUpload', partnerKycUpload)
partnerRoutes.post('/addProperty', addProperty)
partnerRoutes.get('/myProperty/:partnerId', partnerTokenVerified, listProperty)
partnerRoutes.get('/propertyDetail/:propertyId', partnerTokenVerified, detailProperty)
partnerRoutes.get('/findPartner', partnerTokenVerified, findParnter)
partnerRoutes.patch('/updateProfile',partnerTokenVerified, partnerProfile)
partnerRoutes.patch('/partnerImage',partnerTokenVerified, partnerimage)
partnerRoutes.patch('/addDescription',partnerTokenVerified, addDescription)
partnerRoutes.get('/findProperty/:id',partnerTokenVerified, findProperty)
partnerRoutes.patch('/updateProperty/:id',partnerTokenVerified, updateProperty)
partnerRoutes.patch('/deletePropertyImage/:id',partnerTokenVerified,deletepropertyImage)
partnerRoutes.get('/fetchBuyers/:partnerId',partnerTokenVerified,fetchBuyer)
partnerRoutes.post('/hideProperty',partnerTokenVerified,hideTheProperty)
partnerRoutes.post('/resentOtp',resendOpt)


module.exports = partnerRoutes;    